### ISSUE TITLE
make command line workflow work on Windows

### ISSUE THREAD

**Issue by max-mapper** [max-mapper/voxel-hello-world#14]
there are issues with code portability, particularly with the current `npm start` command. might be an upstream bug with browservefy etc

**Comment by max-mapper** [comment]
@sdjidjev can you do me a favor and test `npm install` and `npm start` again on windows? this commit I just made might have fixed the problem we were having the other night https://github.com/maxogden/voxel-hello-world/commit/0ff500d3d150152adfbc0f77207c225a5a00f35f

thanks!

**Comment by sdjidjev** [comment]
@maxogden  `npm install` and `npm start` both run fine without any noticeable errors. I was able to run it on my localhost, but I wasn't able to use `make` to try running our project on the server.

**Comment by max-mapper** [comment]
@sdjidjev cool, thanks! the makefile still has `/` forward slashes hardcoded in it, maybe it works if you replace those with `\`
