### ISSUE TITLE
invisible textures with three.js r55/r56

### ISSUE THREAD

**Issue by max-mapper** [max-mapper/voxel-hello-world#17]
![Screen Shot 2013-03-12 at 3 43 24 PM](https://f.cloud.github.com/assets/39759/251446/4fa71654-8b66-11e2-81ba-92ee8a79f27b.png)

also a mysterious `<pre>` gets added to the page...

to reproduce: 

clone this repo, npm install && npm start

**Comment by max-mapper** [comment]
cc @shama

**Comment by shama** [comment]
Just an update. I don't think it's the textures. The materials get applied correctly to other geometries. I think something is going on in the mesher. All of the `vertexColors` on a mesh are the same. Will continue to look into why.

**Comment by jeromeetienne** [comment]
according to webgl inspector, no texture is uploaded to gpu. so it would not be invisible but inexistant from a gpu point of view

**Comment by jeromeetienne** [comment]
putting everybody on three r56 and voxel-engine 0.14.1 helps. no more webgl warning. and the game is actually running. highlighter + character are seen. but still no voxel

**Comment by timoxley** [comment]
more evidence it's not a texture issue: `new Game({meshType: 'wireMesh'…` also has same behaviour

**Comment by timoxley** [comment]
Got it… `voxel-mesh` doesn't use the game's THREE instance, and is using the old THREE version.

**Comment by timoxley** [comment]
peer dependencies perhaps?

**Comment by max-mapper** [comment]
BAHHH ok fixing. and adding peerdeps

**Comment by shama** [comment]
Nice catch @timoxley!
